name: task2-profiles
services:
  web:
    command:
      - sh
      - -c
      - pip install flask && python app.py
    image: python:3.12-slim
    networks:
      default: null
    ports:
      - mode: ingress
        target: 6000
        published: "6000"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/palyha/lab08/task2-profiles/app
        target: /app
        bind: {}
    working_dir: /app
networks:
  default:
    name: task2-profiles_default
