name: task1-build
services:
  app:
    build:
      context: /home/palyha/lab08/task1-build/app
      dockerfile: Dockerfile
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
networks:
  default:
    name: task1-build_default
