services:
  web:
    image: python:3.12-slim
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install flask && python app.py"
    ports:
      - "6000:6000"
  redis:
    image: redis:7
    profiles:
      - cache
  monitor:
    image: netdata/netdata
    profiles:
      - monitor
    ports:
      - "19999:19999"
